# -*- coding: utf-8 -*-
"""Extracción

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ew2Z3F-I4C2jvg_jYiTYCiY-DeXdYLE0

# Pre Work

## Mount Drive
"""

from google.colab import drive
drive.mount('/content/drive/')

"""## Import Libraries"""

pip install pdfplumber

import pdfplumber
import pandas as pd
from tqdm import tqdm
import pdfplumber

"""##Import data"""

# Ruta de archivos en Drive.
ruta_aptos = "/content/drive/MyDrive/Proyecto SQL/Base de Datos/Anexo n° 1 – Relación de postulantes aptos para rendir el ENP.pdf"
ruta_preseleccionados = "/content/drive/MyDrive/Proyecto SQL/Base de Datos/Anexo n° 1 – Relación de postulantes preseleccionados.pdf"
ruta_seleccionados_1 = "/content/drive/MyDrive/Proyecto SQL/Base de Datos/Anexo n° 1 – Lista de postulantes seleccionados - 1° Momento.pdf"
ruta_seleccionados_2 = "/content/drive/MyDrive/Proyecto SQL/Base de Datos/Anexo n° 2 – Lista de postulantes seleccionados - 2° Momento.pdf"
ruta_1_becarios_1 = "/content/drive/MyDrive/Proyecto SQL/Base de Datos/Anexo n° 1 – Primera relación de becarios - Primer Momento.pdf"
ruta_2_becarios_1 = "/content/drive/MyDrive/Proyecto SQL/Base de Datos/Anexo n° 2 – Segunda relación de becarios - Primer Momento.pdf"
ruta_3_becarios_1 = "/content/drive/MyDrive/Proyecto SQL/Base de Datos/Anexo n° 3 – Tercera relación de becarios - Primer Momento.pdf"
ruta_4_becarios_1 = "/content/drive/MyDrive/Proyecto SQL/Base de Datos/Anexo n° 4 – Cuarta relación de becarios - Primer Momento.pdf"
ruta_1_becarios_2 = "/content/drive/MyDrive/Proyecto SQL/Base de Datos/Anexo n° 1 – Primera relación de becarios - Segundo Momento.pdf"

"""## Extracción de Tablas - Aptos"""

Aptos = []

with pdfplumber.open(ruta_aptos) as pdf:
    for i, page in enumerate(tqdm(pdf.pages)):
        try:
            table = page.extract_table()

            if table:
                for row in table[1:]:
                    Aptos.append(row)

        except Exception as e:
            print(f"Error en página {i}: {e}")

# Crear DataFrame SIN usar encabezados del PDF
df_aptos = pd.DataFrame(Aptos)

# Asignar encabezados normalizados
df_aptos.columns = ["N", "MODALIDAD", "DNI", "NOMBRES", "RESULTADO"]

# Limpiar DNI
df_aptos["DNI"] = df_aptos["DNI"].astype(str).str.replace(" ", "").str.strip()

# Limpiar textos
df_aptos["MODALIDAD"] = df_aptos["MODALIDAD"].str.upper().str.strip()
df_aptos["NOMBRES"] = df_aptos["NOMBRES"].str.strip()
df_aptos["RESULTADO"] = df_aptos["RESULTADO"].str.strip()

# Eliminar filas basura (headers repetidos o errores)
df_aptos = df_aptos[df_aptos["DNI"].str.len() == 8]

# Eliminar nulos
df_aptos = df_aptos.dropna()

ruta_salida = "/content/drive/MyDrive/Proyecto SQL/Base de Datos/aptos.csv"

df_aptos.to_csv(
    ruta_salida,
    index=False,
    encoding="utf-8-sig"
)

print("✅ Archivo CSV exportado correctamente")

df_aptos.info()

"""## Extracción de Tablas - Preseleccionados"""

data_preseleccionados = []

with pdfplumber.open(ruta_preseleccionados) as pdf:
    for i, page in enumerate(tqdm(pdf.pages)):
        try:
            table = page.extract_table()

            if table:
                for row in table[1:]:  # ignoramos encabezados

                    # Ignorar filas vacías
                    if not row or all(x is None for x in row):
                        continue

                    # Caso correcto (9 columnas)
                    if len(row) == 9:
                        data_preseleccionados.append(row)

                    # Caso con columna extra (POBLACIÓN)
                    elif len(row) == 10:
                        # Eliminamos la columna extra (posición 2 o 3)
                        nueva_fila = row[:2] + row[3:]
                        data_preseleccionados.append(nueva_fila)

                    else:
                        print(f"⚠️ Fila irregular en página {i}: {row}")

        except Exception as e:
            print(f"❌ Error en página {i}: {e}")

df_preseleccionados.info()

df_preseleccionados[
    pd.to_numeric(df_preseleccionados["N"], errors="coerce").notna()
].head()

df_preseleccionados[
    df_preseleccionados["N"].str.contains("1844", na=False)
].head()

df_preseleccionados = pd.DataFrame(data_preseleccionados)

df_preseleccionados.columns = [
    "N",
    "MODALIDAD",
    "DNI",
    "NOMBRES",
    "REGION",
    "PUNTAJE_ENP",
    "CONDICIONES",
    "PUNTAJE_FINAL",
    "RESULTADO"
]

# 🔥 1. Eliminar saltos de línea en todo el DataFrame
df_preseleccionados = df_preseleccionados.applymap(
    lambda x: x.replace("\n", " ").strip() if isinstance(x, str) else x
)

# 🔥 2. Normalizar espacios múltiples
df_preseleccionados = df_preseleccionados.applymap(
    lambda x: " ".join(x.split()) if isinstance(x, str) else x
)

# DNI limpio
df_preseleccionados["DNI"] = df_preseleccionados["DNI"].astype(str).str.strip()

# textos
df_preseleccionados["MODALIDAD"] = df_preseleccionados["MODALIDAD"].str.upper().str.strip()
df_preseleccionados["NOMBRES"] = df_preseleccionados["NOMBRES"].str.strip()
df_preseleccionados["REGION"] = df_preseleccionados["REGION"].str.strip()

# 🔥 Normalizar CNA
df_preseleccionados["MODALIDAD"] = df_preseleccionados["MODALIDAD"].str.replace(
    r"BECA CNA Y POBLACIONES.*AFROPERUANAS",
    "BECA CNA Y PA",
    regex=True
)

# convertir puntajes
df_preseleccionados["PUNTAJE_ENP"] = pd.to_numeric(df_preseleccionados["PUNTAJE_ENP"], errors="coerce")
df_preseleccionados["CONDICIONES"] = pd.to_numeric(df_preseleccionados["CONDICIONES"], errors="coerce")
df_preseleccionados["PUNTAJE_FINAL"] = pd.to_numeric(df_preseleccionados["PUNTAJE_FINAL"], errors="coerce")

# eliminar registros inválidos
df_preseleccionados = df_preseleccionados[df_preseleccionados["DNI"].str.len() == 8]

# eliminar nulos
df_preseleccionados = df_preseleccionados.dropna()

df_preseleccionados[
    df_preseleccionados["N"].str.contains("6165", na=False)
].head()

ruta_salida = "/content/drive/MyDrive/Proyecto SQL/Base de Datos/preseleccionados.csv"

df_preseleccionados.to_csv(
    ruta_salida,
    index=False,
    encoding="utf-8-sig"
)

print("✅ Preseleccionados exportado correctamente")

df_preseleccionados.info()

"""## Extracción de Tablas - Seleccionados 1 y 2"""

def extraer_seleccionados(ruta_pdf):
    data = []

    with pdfplumber.open(ruta_pdf) as pdf:
        for i, page in enumerate(tqdm(pdf.pages)):
            try:
                table = page.extract_table()

                if table:
                    for row in table[1:]:

                        # Ignorar filas vacías
                        if not row or all(x is None for x in row):
                            continue

                        # 🔥 Caso normal (11 columnas)
                        if len(row) == 11:
                            data.append(row)

                        # 🔥 Caso con POBLACIÓN (12 columnas)
                        elif len(row) == 12:
                            # eliminamos la columna extra (posición 2 o 3)
                            nueva_fila = row[:2] + row[3:]
                            data.append(nueva_fila)

                        else:
                            print(f"⚠️ Fila irregular en página {i}: {row}")

            except Exception as e:
                print(f"❌ Error en página {i}: {e}")

    # Crear DataFrame
    df = pd.DataFrame(data)

    # Asignar columnas
    df.columns = [
        "N",
        "MODALIDAD",
        "DNI",
        "NOMBRES",
        "IES",
        "SEDE",
        "CARRERA",
        "CONCEPTO_A",
        "CONCEPTO_B",
        "PUNTAJE_FINAL",
        "CONDICION"
    ]

    return df

df_seleccionados_1 = extraer_seleccionados(ruta_seleccionados_1)
df_seleccionados_2 = extraer_seleccionados(ruta_seleccionados_2)

def limpiar_seleccionados(df):

    # 🔥 1. Limpiar saltos de línea en TODO el DataFrame
    df = df.applymap(lambda x: x.replace("\n", " ").strip() if isinstance(x, str) else x)

    # 🔥 2. Normalizar espacios múltiples
    df = df.applymap(lambda x: " ".join(x.split()) if isinstance(x, str) else x)

    # DNI limpio
    df["DNI"] = df["DNI"].astype(str).str.strip()

    # textos
    df["MODALIDAD"] = df["MODALIDAD"].str.upper().str.strip()
    df["NOMBRES"] = df["NOMBRES"].str.strip()
    df["IES"] = df["IES"].str.strip()
    df["CARRERA"] = df["CARRERA"].str.strip()

    # 🔥 3. Normalizar CNA (versión robusta)
    df["MODALIDAD"] = df["MODALIDAD"].str.replace(
        r"BECA CNA Y POBLACIONES.*AFROPERUANAS",
        "BECA CNA Y PA",
        regex=True
    )

    # convertir puntajes
    df["CONCEPTO_A"] = pd.to_numeric(df["CONCEPTO_A"], errors="coerce")
    df["CONCEPTO_B"] = pd.to_numeric(df["CONCEPTO_B"], errors="coerce")
    df["PUNTAJE_FINAL"] = pd.to_numeric(df["PUNTAJE_FINAL"], errors="coerce")

    # eliminar basura
    df = df[df["DNI"].str.len() == 8]
    df = df.dropna()

    # 🔥 4. Convertir a ENTEROS
    df["CONCEPTO_A"] = df["CONCEPTO_A"].astype(int)
    df["CONCEPTO_B"] = df["CONCEPTO_B"].astype(int)
    df["PUNTAJE_FINAL"] = df["PUNTAJE_FINAL"].astype(int)

    return df

df_seleccionados_1 = limpiar_seleccionados(df_seleccionados_1)
df_seleccionados_2 = limpiar_seleccionados(df_seleccionados_2)

print("Primer momento:", df_seleccionados_1.shape)
print("Segundo momento:", df_seleccionados_2.shape)

df_seleccionados_1.head()
df_seleccionados_2.head()

df_seleccionados_1.to_csv(
    "/content/drive/MyDrive/Proyecto SQL/Base de Datos/seleccionados_1.csv",
    index=False,
    encoding="utf-8-sig"
)

df_seleccionados_1.info()

df_seleccionados_2.to_csv(
    "/content/drive/MyDrive/Proyecto SQL/Base de Datos/seleccionados_2.csv",
    index=False,
    encoding="utf-8-sig"
)

df_seleccionados_2.info()

df_seleccionados_2[
    df_seleccionados_2["MODALIDAD"].str.contains("CNA", na=False)
].head()

"""## Extracción de Tablas - Becarios

"""

def extraer_becarios(ruta_pdf):
    data = []

    with pdfplumber.open(ruta_pdf) as pdf:
        for i, page in enumerate(tqdm(pdf.pages)):
            try:
                table = page.extract_table()

                if table:
                    for row in table[1:]:

                        # Ignorar filas vacías
                        if not row or all(x is None for x in row):
                            continue

                        # Solo filas correctas (8 columnas)
                        if len(row) == 8:
                            data.append(row)
                        else:
                            print(f"⚠️ Fila irregular en página {i}: {row}")

            except Exception as e:
                print(f"❌ Error en página {i}: {e}")

    df = pd.DataFrame(data)

    df.columns = [
        "N",
        "MODALIDAD",
        "DNI",
        "NOMBRES",
        "INSTITUCION",
        "SEDE",
        "CARRERA",
        "CONDICION"
    ]

    return df

def limpiar_becarios(df):

    # 🔥 eliminar saltos de línea
    df = df.applymap(lambda x: x.replace("\n", " ").strip() if isinstance(x, str) else x)

    # 🔥 normalizar espacios
    df = df.applymap(lambda x: " ".join(x.split()) if isinstance(x, str) else x)

    # DNI limpio
    df["DNI"] = df["DNI"].astype(str).str.strip()

    # textos
    df["MODALIDAD"] = df["MODALIDAD"].str.upper().str.strip()
    df["NOMBRES"] = df["NOMBRES"].str.strip()
    df["INSTITUCION"] = df["INSTITUCION"].str.strip()
    df["CARRERA"] = df["CARRERA"].str.strip()

    # 🔥 normalizar CNA
    df["MODALIDAD"] = df["MODALIDAD"].str.replace(
        r"BECA CNA Y POBLACIONES.*AFROPERUANAS",
        "BECA CNA Y PA",
        regex=True
    )

    # eliminar basura
    df = df[df["DNI"].str.len() == 8]
    df = df.dropna()

    return df

df_becarios_1_1 = limpiar_becarios(extraer_becarios(ruta_1_becarios_1))
df_becarios_2_1 = limpiar_becarios(extraer_becarios(ruta_2_becarios_1))
df_becarios_3_1 = limpiar_becarios(extraer_becarios(ruta_3_becarios_1))
df_becarios_4_1 = limpiar_becarios(extraer_becarios(ruta_4_becarios_1))
df_becarios_1_2 = limpiar_becarios(extraer_becarios(ruta_1_becarios_2))

df_becarios_1_1.to_csv("/content/drive/MyDrive/Proyecto SQL/Base de Datos/becarios_1_1.csv", index=False, encoding="utf-8-sig")
df_becarios_2_1.to_csv("/content/drive/MyDrive/Proyecto SQL/Base de Datos/becarios_2_1.csv", index=False, encoding="utf-8-sig")
df_becarios_3_1.to_csv("/content/drive/MyDrive/Proyecto SQL/Base de Datos/becarios_3_1.csv", index=False, encoding="utf-8-sig")
df_becarios_4_1.to_csv("/content/drive/MyDrive/Proyecto SQL/Base de Datos/becarios_4_1.csv", index=False, encoding="utf-8-sig")
df_becarios_1_2.to_csv("/content/drive/MyDrive/Proyecto SQL/Base de Datos/becarios_1_2.csv", index=False, encoding="utf-8-sig")

df_becarios_1_1["MODALIDAD"].value_counts()

df_becarios_1_1.info()
